.pre-commit-config.yaml, README.md, evaluation-tasks/README.md, evaluation-tasks/coughvid.py
This is a basic skeleton for a pipeline to download and preprocess Coughvid data. There are a handful of TODO items left, but this code works and the individual tasks it performs are correct.
It's WIP because evaluation metadata is not here yet.
=> [WIP] Luigi pipeline for Coughvid

evaluation-tasks/coughvid.py, evaluation-tasks/util/luigi.py
This should make it easier when developing Luigi to delete the last K task outputs.
=> Add stage number to Luigi workdir

evaluation-tasks/coughvid.py
* ResampleCorpus tasks were all using the same output name, which was a bug.
* All tasks names are now verbs
=> Bugfix and renames

evaluation-tasks/luigi.cfg
Not sure we want to set the logging level to INFO quite yet -- but this makes the print out from luigi much nicer
=> Luigi config + luigi logging level

evaluation-tasks/coughvid.py
Filter only files with labels, merges into https://github.com/neuralaudio/hear2021-eval-kit/pull/17
Closes https://github.com/neuralaudio/hear2021-eval-kit/issues/16
=> Filter files with labels

heareval/tasks/coughvid.py
This unbreaks the checkpoints, which stopped working temporarily after I added mypy tweaks
=> Fixes to Coughvid checkpointing

heareval/embeddings/task_embeddings.py, heareval/tasks/dcase2016_task2.py, heareval/tasks/nsynth_pitch.py, heareval/tasks/pipeline.py, heareval/tasks/speech_commands.py
=> embedding_type and prediction_type

heareval/embeddings/task_embeddings.py, heareval/tasks/README.md, heareval/tasks/dcase2016_task2.py
=> Event timestamps in MS

heareval/tasks/dcase2016_task2.py, heareval/tasks/nsynth_pitch.py, heareval/tasks/pipeline.py, heareval/tasks/speech_commands.py, heareval/tasks/util/luigi.py
=> Added md5 checking

heareval/embeddings/task_embeddings.py
For the concatenated version of all the frames, we need a file mapping each frame to the filename and timestamp. This will be used for DCASE and event eval.
=> Save event timestamps for memmaped file

heareval/embeddings/task_embeddings.py, heareval/tasks/pipeline.py
Closes https://github.com/neuralaudio/hear-eval-kit/issues/124
=> List for scene classes

heareval/predictions/task_predictions.py
Smooths frame-level event predictions prior to computing timestamped events. Also filters on event duration and rejects events below a certain theshold. This is based on the post-processing computed by the [DCASE2016 Task 2 baseline](http://dcase.community/challenge2016/task-sound-event-detection-in-synthetic-audio#baseline-results-for-development-set)
=> Event Prediction Smoothing

heareval/embeddings/task_embeddings.py, heareval/predictions/task_predictions.py
For event predictions this converts a set of frame based label predictions to a list of events with start and stop timestamps in ms.
=> Event prediction

README.md, requirements.txt, setup.py
Closes #154 #155 #156
Thank you to @auroracrammer for finding these issues.
=> Updated install instructions

README.md, heareval/tasks/nsynth_pitch.py, heareval/tasks/sampler.py
Builds a sampler for the dataset
- Uses the same download and extract tasks to make sure the same downloaded files can be used for sampling
- Also uses the configs defined in the task files for making it simple to scale across multiple datasets
=> Sample dataset Task

heareval/predictions/runner.py, heareval/predictions/task_predictions.py, requirements.txt, setup.py
Unfortunately, we skip dcase because it doesn't have a validation set. https://github.com/neuralaudio/hear-eval-kit/issues/94
=> Learn the predictor

.travis.yml, README.md
Massive Travis CI matrix, just for preprocessing, not downstream evaluation yet.
=> [WIP] Travis CI for preprocessing

heareval/tasks/dcase2016_task2.py, heareval/tasks/pipeline.py
=> Fix Unique Slug

.pre-commit-config.yaml, Dockerfile, README.md, heareval/embeddings/task_embeddings.py, heareval/predictions/runner.py, heareval/predictions/task_predictions.py, requirements.txt, setup.py, spotty.yaml
Also enable GPU, and wandb logging.
=> Grid search for predictor

.gitmodules, docker/Dockerfile-cuda10.2, docker/Dockerfile-cuda11.2, docker/README.md, docker/build.sh, heareval/embeddings/task_embeddings.py, spotty.yaml
I am trying to get CUDA 11.2 working, which hopefully supports both latest pytorch and TF with GPU
=> Dockerfiles

heareval/tasks/runner.py, heareval/tasks/sampler.py
Adds the path to the submodule in the runner so that submodule can work without installing.
=> Add path to submodule

heareval/embeddings/task_embeddings.py, heareval/predictions/task_predictions.py, requirements.txt, setup.py
DCASE looks fine so far. I fix a tiny bug that the end timestamp wasn't included in the labels
=> Dcase debug

heareval/embeddings/task_embeddings.py, heareval/predictions/task_predictions.py
We won't use this for the final leaderboard. Instead, we'll make a much tighter grid by running these on strong benchmarks.
=> Much bigger gridsearch

docker/Dockerfile-cuda11.2, heareval/embeddings/runner.py, heareval/embeddings/task_embeddings.py, heareval/predictions/task_predictions.py, heareval/tasks/pipeline.py
If you want to pass in undocumented model options, here it is. Mainly for model parameters that are not stored in the weights file
=> Model options (undocumented)

heareval/embeddings/task_embeddings.py, heareval/predictions/runner.py, heareval/predictions/task_predictions.py
This adds a handful of options to the predictor:
* Deterministic or not
* Number of grid points
* model_options, if you have non-model path options to control your model
It also includes more diagnostics, and adjusts the batch size based upon current runs.
=> More predictor options

heareval/gpu_max_mem.py, heareval/predictions/task_predictions.py
This works, it's just got a lot of debug output so I can test it on GPUs.
This code is gnarly and I wish I could simplify it :(
=> [WIP] Test finally works correctly, and event filtering
